name = "ArgParse2"
uuid = "1f1e2b29-1d7f-49d8-813e-55fc6f50152b"
authors = ["Kevin Squire"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
